       FUNCTION CHIMA_FUNC(NDIM,X,EVAP)
       INTEGER NATOMS,NDIM,SW
       REAL*8 CHIMA_FUNC,X(NDIM),RADIUS,NONE1
       REAL*8 EREAL1
       COMMON /cgsw/ SW
       COMMON /accuracy3/ RADIUS,NONE1
       LOGICAL EVAP
       NATOMS=NDIM/3
       CALL CHIMA(NATOMS,X,EREAL1,EVAP)
       CHIMA_FUNC=EREAL1
       RETURN
       END
