        SUBROUTINE DIH(NATOMS,X,ENR)
        INTEGER NATOMS,J1,J3,SW,I_TYPE(1000),TYPE
        REAL*8 X(NATOMS*3),ENR,R3,A0,A1,A2,A3,A4,A5,B1,B2
        REAL*8 D11,D12,D13,D21,D22,D23,D31,D32,D33,SQR_ABC
        REAL*8 CROSS_ABCX,CROSS_ABCY,CROSS_ABCZ,MAG_CRO_AB
        REAL*8 CROSS_BCDX,CROSS_BCDY,CROSS_BCDZ,MAG_CRO_BC
        REAL*8 CROSS_ABCDX,CROSS_ABCDY,CROSS_ABCDZ,MAG_ABCD
        REAL*8 CRO_AB_DOT_CRO_BC,SIN_PHID,SIN_PHID2,SIN_PHID3
        REAL*8 COS_PHID,COS_PHID2,COS_PHID3,COS3DTH
        REAL*8 ACOIL,BCOIL,CCOIL,DCOIL,DSQ2
        COMMON /cgsw/ SW
        COMMON /engtype/ TYPE
        COMMON /INTER_TYPE1/ I_TYPE
        COMMON /DIH1/ ACOIL,BCOIL,CCOIL,DCOIL,R3,A0,A1,A2,A3,A4,A5,B1,B2
C   I_TYPE=1   B
C   I_TYPE=2   L
C   I_TYPE=3   N
        ENR=0.D0
        DO J1=1,NATOMS-3
          J3=J1*3
          D11=X(J3+1)-X(J3-2)
          D12=X(J3+2)-X(J3-1)
          D13=X(J3+3)-X(J3)
          D21=X(J3+4)-X(J3+1)
          D22=X(J3+5)-X(J3+2)
          D23=X(J3+6)-X(J3+3)
          D31=X(J3+7)-X(J3+4)
          D32=X(J3+8)-X(J3+5)
          D33=X(J3+9)-X(J3+6)

          CROSS_ABCX=D12*D23-D13*D22
          CROSS_ABCY=D13*D21-D11*D23
          CROSS_ABCZ=D11*D22-D12*D21

          CROSS_BCDX=D33*D22-D32*D23
          CROSS_BCDY=D31*D23-D33*D21
          CROSS_BCDZ=D32*D21-D31*D22

          CROSS_ABCDX=CROSS_ABCY*CROSS_BCDZ-CROSS_ABCZ*CROSS_BCDY
          CROSS_ABCDY=CROSS_ABCZ*CROSS_BCDX-CROSS_ABCX*CROSS_BCDZ
          CROSS_ABCDZ=CROSS_ABCX*CROSS_BCDY-CROSS_ABCY*CROSS_BCDX

          MAG_ABCD=CROSS_ABCDX**2.+CROSS_ABCDY**2.+CROSS_ABCDZ**2.

          CRO_AB_DOT_CRO_BC=CROSS_ABCX*CROSS_BCDX
     &                     +CROSS_ABCY*CROSS_BCDY
     &                     +CROSS_ABCZ*CROSS_BCDZ

          MAG_CRO_AB=CROSS_ABCX**2.+CROSS_ABCY**2.+CROSS_ABCZ**2.

          MAG_CRO_BC=CROSS_BCDX**2.+CROSS_BCDY**2.+CROSS_BCDZ**2.

          SQR_ABC=DSQRT(MAG_CRO_AB*MAG_CRO_BC)

          SIN_PHID=DSQRT(MAG_ABCD)/SQR_ABC
          SIN_PHID2=SIN_PHID**2.
          SIN_PHID3=SIN_PHID2*SIN_PHID

          COS_PHID=(CRO_AB_DOT_CRO_BC)/SQR_ABC
          COS_PHID2=COS_PHID**2.
          COS_PHID3=COS_PHID*COS_PHID2

          COS3DTH=4.D0*COS_PHID3-3.D0*COS_PHID
          IF (I_TYPE(J1).NE.3.AND.I_TYPE(J1+1).NE.3.AND.
     &    I_TYPE(J1+2).NE.3)THEN
            IF (TYPE.EQ.3)THEN
              ENR=ENR+ACOIL*(1.D0+COS_PHID)+BCOIL*(1.D0+COS3DTH)
            ENDIF
            IF (TYPE.EQ.4)THEN
              DSQ2=DSQRT(2.D0)
              ENR=ENR+ACOIL*(1.-COS_PHID)+BCOIL*(1.+COS3DTH)
     &  +CCOIL*(1.+(1./DSQ2)*COS_PHID-(1./DSQ2)*SIN_PHID)
            ENDIF
          ENDIF
          IF ((I_TYPE(J1).EQ.3.AND.I_TYPE(J1+1).EQ.3.AND.
     & I_TYPE(J1+2).NE.3.AND.I_TYPE(J1+3).NE.3).OR.(I_TYPE(J1).EQ.
     & 3.AND.I_TYPE(J1+1).EQ.3.AND.I_TYPE(J1+2).EQ.3))THEN     
            IF (TYPE.EQ.3.OR.TYPE.EQ.4)THEN
              ENR=ENR+DCOIL*(1.D0+COS3DTH)
            ENDIF
          ENDIF
          IF (TYPE.EQ.5.AND.((I_TYPE(J1).EQ.3.AND.I_TYPE(J1+1).EQ.3).OR.
     &(I_TYPE(J1+2).EQ.3.AND.I_TYPE(J1+3).EQ.3)))THEN
            ENR=ENR+ACOIL*(1.D0+COS_PHID)+BCOIL*(1.D0+COS3DTH)
          ELSE
            ENR=ENR+A0+A1*COS_PHID+A2*COS_PHID2+A3*COS_PHID3
     &         +A4*(COS_PHID2**2.)+A5*COS_PHID2*COS_PHID3
     &         +B1*SIN_PHID3+B2*SIN_PHID3*SIN_PHID2
          ENDIF
       ENDDO
       RETURN
       END
